<?php
/**
 * Allows redirect to Secure Form
 * 
 * @link http://devzone.paylane.pl/secure-form/
 * @see Endora_PayLane_Block_Form
 * @author Michał Zabielski <michal.zabielski@endora.pl> http://www.endora.pl
 */
?>
<?php
    $paymentMethods = $this->getPaymentMethods();
    $onlyOnePaymentActive = 0; //means false
    $onlyOnePaymentCode = '';
?>
<div class="paylane-payment-container">
    <div id="payment_form_paylane">
        <?php if(count($paymentMethods) > 1): ?>
        <div class="paylane-payment-method-container-title"><?php echo $this->__('Choose payment method'); ?>:</div>
        <div class="paylane-payment-method-container">
            <ul class="form-list">
            <?php foreach($paymentMethods as $code => $method): ?>
                <li <?php if(!empty($method['img'])): ?>class="with-image"<?php endif; ?>>
                    <input type="radio" name="payment[additional_information][paylane_payment_type]" id="paylane_payment_type_<?php echo $code; ?>" value="<?php echo $code; ?>" />
                    <label for="paylane_payment_type_<?php echo $code; ?>">
                        <?php if(empty($method['img'])): ?>
                            <?php echo $this->__($method['label']); ?>
                        <?php else: ?>
                            <?php if(!empty($method['img'])): ?>
                                <div class="img-wrapper">
                            <?php endif; ?>
                                <img src="<?php echo $method['img']; ?>" title="<?php echo $this->__($method['label']); ?>" alt="<?php echo $this->__($method['label']); ?>" />
                            <?php if(!empty($method['img'])): ?>
                                </div>
                            <?php endif; ?>
                            <span><?php echo $this->__($method['label']); ?></span>
                        <?php endif; ?>
                    </label>
                </li>
            <?php endforeach; ?>
            </ul>
            <div class="clearfix"></div>
        </div>
        <?php endif; ?>
        <?php if(count($paymentMethods) == 1): ?>
            <?php foreach($paymentMethods as $code => $method): ?>
                <?php $onlyOnePaymentActive = true; $onlyOnePaymentCode = $code;?>
                <input type="hidden" name="payment[additional_information][paylane_payment_type]" id="paylane_payment_type_<?php echo $code; ?>" value="<?php echo $code; ?>" />
            <?php endforeach; ?>
        <?php endif; ?>
        <?php if(count($paymentMethods) < 1): ?>
        <div class="paylane-payment-method-container-title"><?php echo $this->__('There are no active payment methods! Please contact with store administrator'); ?>:</div>
        <?php endif; ?>
        <div id="paylane-payment-method-additional-container"><?php //load via AJAX request is performed ?></div>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    function fetchPaymentTemplate(paymentType) {
        jQuery.post( "<?php echo Mage::getUrl('paylane/payment/fetchPaymentTemplate'); ?>", { paymentType : paymentType }).done(function (data) {
            jQuery("#payment-buttons-container button:first").removeAttr("disabled");
            jQuery("#paylane-payment-method-additional-container").html(data);
        });
    }

    if(jQuery('input[type=radio][name="payment[method]"]:checked').val() === "paylane") {
        jQuery(".paylane-payment-container").show();
        if(<?php echo $onlyOnePaymentActive; ?>) {
            fetchPaymentTemplate(jQuery('input[name="payment[additional_information][paylane_payment_type]"]').val());
        }
    }
    
    jQuery('input[type=radio][name="payment[method]"]').change(function() {
       if(this.value === "paylane") {
           if(<?php echo $onlyOnePaymentActive; ?>) {
               fetchPaymentTemplate(jQuery('input[name="payment[additional_information][paylane_payment_type]"]').val());
               jQuery(".paylane-payment-container").show();
           } else {
               jQuery(".paylane-payment-container").slideDown();
           }
       } else {
           jQuery(".paylane-payment-container").slideUp();
       }
    });
    
    jQuery('input[type=radio][name="payment[additional_information][paylane_payment_type]"]').change(function() {
        var paymentType = this.value;
        fetchPaymentTemplate(paymentType);
    });
//]]>
</script>
