<?php
/**
 * Display list of payment types for bank transfer
 * 
 * @author Michał Zabielski <michal.zabielski@endora.pl> http://www.endora.pl
 */
?>
<?php $paymentTypes = $this->getPaymentTypes(); ?>
<div class="paylane-payment-method-container-title"><?php echo $this->__('Choose payment type'); ?>:</div>
<ul class="form-list payment-types-list bank-transfer">
<?php foreach($paymentTypes as $code => $data): ?>
    <li>
        <input type="radio" name="payment[additional_information][payment_type]" id="payment_type_<?php echo $code; ?>" value="<?php echo $code; ?>">
        <label for="payment_type_<?php echo $code; ?>">
            <img src="<?php echo $this->getBankImageUrl($code); ?>" title="<?php echo $this->__($data['label']); ?>" alt="<?php echo $this->__($data['label']); ?>" />
            <span><?php echo $this->__($data['label']); ?></span>
        </label>
    </li>
<?php endforeach; ?>
</ul>
<div class="clearfix"></div>
