<?php 
    $helper = Mage::helper('paylane');
    $isSingleClickActive = $helper->isSingleClickActive();
    $isAuthorized = $this->isCustomerAuthorized(); 
    $isFirstOrder = $this->isCustomerFirstOrder();
    $months = $helper->generateMonthsNumber();
    $years = $helper->generateCreditCardValidYears();
?>
<?php if(!$isSingleClickActive || ($isSingleClickActive && $isFirstOrder)): ?>
<div class="form-list">
    <div class="field">
        <label for="payment_params_card_number" class="required"><em>*</em><?php echo $this->__('Card number'); ?></label>
        <div class="input-box">
            <input type="text" id="payment_params_card_number" size="19" class="input-text required-entry">
        </div>
    </div>
    <div class="field">
        <label for="payment_params_name_on_card" class="required"><em>*</em><?php echo $this->__('Name on card'); ?></label>
        <div class="input-box">
            <input type="text" id="payment_params_name_on_card" size="50" class="input-text required-entry">
        </div>
    </div>
    <div class="field">
        <label for="payment_params_expiration_month" class="required"><em>*</em><?php echo $this->__('Expiration month'); ?></label>
        <div class="input-box">
            <select id="payment_params_expiration_month" class="required-entry">
                <?php foreach($months as $month): ?>
                    <option value="<?php echo $month; ?>"><?php echo $month; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="field">
        <label for="payment_params_expiration_year" class="required"><em>*</em><?php echo $this->__('Expiration year'); ?></label>
        <div class="input-box">
            <select id="payment_params_expiration_year" class="required-entry">
            <?php foreach($years as $year): ?>
                <option value="<?php echo $year; ?>"><?php echo $year; ?></option>
            <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="field">
        <label for="payment_params_card_code" class="required"><em>*</em><?php echo $this->__('CVV/CVC'); ?></label>
        <div class="input-box">
            <input type="text" id="payment_params_card_code" size="4" class="input-text required-entry">
        </div>
    </div>
    <input type="hidden" id="payment_params_token" name="payment[additional_information][token]" value="">
</div>
<?php else: ?>
    <?php if($isAuthorized): ?>
        <?php $authId = Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getId())
                            ->getCardAuthorizationId();
        ?>
        <input type="hidden" id="payment_params:authorization_id" name="payment[additional_information][authorization_id]" value="<?php echo $authId; ?>">
        <?php echo $this->__('User authorized earlier - no additional data required'); ?>
    <?php else: ?>
        <?php $saleId = $this->getCustomerLastOrderPaylaneSaleId(); ?>
        <input type="hidden" id="payment_params:sale_id" name="payment[additional_information][sale_id]" value="<?php echo $saleId; ?>">
        <?php echo $this->__('Using Single-click method - get card data from earlier order'); ?>
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[
    jQuery("#payment-buttons-container button").on('click', function(ev) {
        var paymentType = jQuery('input[type=radio][name="payment[additional_information][paylane_payment_type]"]:checked');
        if (paymentType.length > 0 && paymentType[0].value === 'creditCard') {
            PayLane.setPublicApiKey("<?php echo $this->getApiKey(); ?>");

            var requestData = {
                cardNumber: jQuery("#payment_params_card_number").val(),
                expirationMonth: jQuery("#payment_params_expiration_month").val(),
                expirationYear: jQuery("#payment_params_expiration_year").val(),
                nameOnCard: jQuery("#payment_params_name_on_card").val(),
                cardSecurityCode: jQuery("#payment_params_card_code").val()
            };

            PayLane.card.generateToken(requestData,
                function(token) {
                    jQuery("#payment_params_token").val(token);
                },
                function(code, result) {}
            );
        }
    });
//]]>
</script>